apiVersion: v1
kind: Service
metadata:
  name: function-pagamento-service
spec:
  type: ClusterIP 
  selector:
    app: function 
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080 