apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jogo
  template:
    metadata:
      labels:
        app: jogo
    spec:
      containers:
        - name: jogo-container
          image: gabrielpaulino/fiapcloudgamesapi:latest
          imagePullPolicy: Always # <--- 
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"