apiVersion: v1
kind: ConfigMap
metadata:
  name: api-usuario-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "fiap-cloud-games"
  Jwt__Audience: "fiap-cloud-games-api"
  RateLimit__MaxRequests: "100"