apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuario-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-usuario
  template:
    metadata:
      labels:
        app: ms-usuario
    spec:
      containers:
      - name: container-api
        image: acrtechchallengefase5.azurecr.io/usuario-api:latest  
        imagePullPolicy: Always   
        ports:
        - containerPort: 8080
        env:

        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-usuario-config
              key: ASPNETCORE_ENVIRONMENT
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: api-usuario-config
              key: Jwt__Issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: api-usuario-config
              key: Jwt__Audience

        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: api-usuario-secret
              key: JwtKey
        - name: ApplicationInsights__ConnectionString
          valueFrom:
            secretKeyRef:
              name: api-usuario-secret
              key: AppInsights
        - name: ConnectionStrings__EventStore
          valueFrom:
            secretKeyRef:
              name: api-usuario-secret
              key: DbEventStore
        - name: ConnectionStrings__ReadModel
          valueFrom:
            secretKeyRef:
              name: api-usuario-secret
              key: DbReadModel
              
        resources:
          requests:   
            cpu: "100m"  
            memory: "64Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"