apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
        - name: pagamento-container
          image: gabrielpaulino/fiapcloudgamesapi:latest
          imagePullPolicy: Always # <---
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"