apiVersion: v1
kind: ConfigMap
metadata:
  name: api-jogos-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  UrlPagamentos: "http://api-pagamento-service" 
  UrlElastic: "http://elasticsearch-service:9200"